### ISSUE TITLE
Drag&Drop issue, when you upload more files while files are still uploading

### ISSUE THREAD

**Issue by mauritznilsson** [CreativeDream/jQuery.filer#102] opened 2016-09-04 12:38 UTC
There is an issue in the drag&drop _(might be an issue with the instant uploading feature)_ example given from the website that if you upload a big file or something that would take a while to complete like multiple medium sized files and then upload more files during that it seems that it adds those files to the old upload queue but since they have already been uploaded once it "duplicates" the files and names them "FILE_NAME (1), FILE_NAME (2), etc..".

_as some additional information when you press the delete button, it deletes the the duplicated file and not the original_

### Second upload completed and there are the files (shown below)
![image](https://cloud.githubusercontent.com/assets/11979966/18230990/4dda1edc-72b4-11e6-8574-8464d4369681.png)
### As shown here
![image](https://cloud.githubusercontent.com/assets/11979966/18230992/552086ae-72b4-11e6-97f3-62833f59090b.png)
### Here we can see that the big file finally completed and then also re-uploaded the already uploaded ones (shown below)
![image](https://cloud.githubusercontent.com/assets/11979966/18230994/5a663762-72b4-11e6-8c57-b0db059438c6.png)
### As shown here
![image](https://cloud.githubusercontent.com/assets/11979966/18230995/5e5b32c8-72b4-11e6-92cf-ad1199fb659d.png)

**Comment by CreativeDream** [comment] 2016-09-12 09:23
@mauritznilsson sorry but I can't reproduce it.

**Comment by mauritznilsson** [comment] 2016-09-12 11:38
@CreativeDream here is a video demonstrating the issue and a link to the jQuery filer 1.2 example I use, all browsers _(Chrome, FireFox and Opera)_ I have tried were able to reproduced this issue.

[Demonstration Video](https://www.youtube.com/watch?v=3anMdyT47DI)
[jQuery Filer 1.2 Example](https://mauritzonline.com/jQuery.filer-1.2/examples/dragdrop/index)

**Comment by CreativeDream** [comment] 2016-09-13 12:18
@mauritznilsson thanks. Will be fixed in v1.3 by inporving `synchron` option.

**Comment by mauritznilsson** [comment] 2016-09-13 13:08
@CreativeDream okay thank you, would you be able to give me a rough estimated time for v1.3 to be released?

**Comment by CreativeDream** [comment] 2016-09-13 13:25
@mauritznilsson in the next 2 days.

**Comment by CreativeDream** [comment] 2016-09-14 07:58
@mauritznilsson <a href="https://github.com/CreativeDream/jQuery.filer/releases/tag/v1.3.0">v1.0.3</a>

**Closed by CreativeDream** 2016-09-14 07:58 UTC
Labels: bug
