### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by blavehuang** [CreativeDream/jQuery.filer#55] opened 2016-01-30 08:47 UTC
the bug film:
https://dl.dropboxusercontent.com/u/14115908/Untitled.mp4

Chrome Version:
47.0.2526.111 m

OS: Windows 7 x64

**Comment by stigfaerch** [comment] 2016-08-09 11:33
I experience the same:
OS: Windows 10 x64
Browser: Edge 25.10586.0.0
Browser: Chrome 52.0.2743.82 m (64-bit)

I could not get this to happen in Firefox.

I also experienced the same on Ubuntu/Chrome

**Comment by CreativeDream** [comment] 2016-08-09 12:18
i know about this issue, but I didn't find any solution yet.

**Comment by PSF1** [comment] 2016-08-18 11:40
Hi, 

I think that the problem is that drop is assigned to the text, don't to the block.

I hope to be helpful.

**Comment by CreativeDream** [comment] 2016-08-18 13:57
@PSF1 i will take a look. thanks

**Comment by CreativeDream** [comment] 2016-08-22 07:51
@blavehuang will be fixed in [v1.2](https://github.com/CreativeDream/jQuery.filer/issues/59)

**Closed by CreativeDream** 2016-08-22 07:51 UTC
